"""empty message

Revision ID: 157d06d5370e
Revises: be36c652a26e
Create Date: 2022-02-07 18:05:30.307632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157d06d5370e'
down_revision = 'be36c652a26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
