"""empty message

Revision ID: be36c652a26e
Revises: fe5eba39f8c4
Create Date: 2022-02-07 18:05:09.162549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be36c652a26e'
down_revision = 'fe5eba39f8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
