"""empty message

Revision ID: fe5eba39f8c4
Revises: 
Create Date: 2022-02-04 11:14:21.279405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe5eba39f8c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('examples', sa.String(), nullable=True),
    sa.Column('author_id', postgresql.UUID(), nullable=False),
    sa.Column('dictionary_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('motd', sa.String(), nullable=True),
    sa.Column('logo_uri', sa.String(), nullable=True),
    sa.Column('custom_colors', sa.JSON(), nullable=True),
    sa.Column('admin_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_table('entries')
    op.drop_table('users')
    op.drop_table('dictionaries')
    # ### end Alembic commands ###
